-- MySQL Script generated by MySQL Workbench
-- Thu Mar 25 10:21:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioalifafa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioalifafa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioalifafa` DEFAULT CHARACTER SET utf8 ;
USE `biblioalifafa` ;

-- -----------------------------------------------------
-- Table `biblioalifafa`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioalifafa`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioalifafa`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioalifafa`.`author` (
  `idauthor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dateofbirth` DATE NULL,
  `dateofdeath` DATE NULL,
  PRIMARY KEY (`idauthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioalifafa`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioalifafa`.`books` (
  `idbook` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `authorid` INT NULL,
  `borrower` VARCHAR(45) NULL,
  PRIMARY KEY (`idbook`),
  INDEX `idauthor_idx` (`authorid` ASC),
  CONSTRAINT `idauthor`
    FOREIGN KEY (`authorid`)
    REFERENCES `biblioalifafa`.`author` (`idauthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioalifafa`.`users_has_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioalifafa`.`users_has_books` (
  `users_idusers` INT NOT NULL,
  `books_idbook` INT NOT NULL,
  `datestart` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `dateend` DATETIME DEFAULT(CURRENT_TIMESTAMP + INTERVAL 1 MONTH),
  `backinstock` TINYINT NULL,
  `users_has_bookscol` VARCHAR(45) NULL,
  PRIMARY KEY (`users_idusers`, `books_idbook`),
  INDEX `fk_users_has_books_books1_idx` (`books_idbook` ASC),
  INDEX `fk_users_has_books_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_users_has_books_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `biblioalifafa`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`books_idbook`)
    REFERENCES `biblioalifafa`.`books` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
